#!/usr/bin/env tsx

import * as path from "path";
import * as fs from "fs";
import { CawsConfigManager } from "./shared/config-manager";

interface InitOptions {
  featureId?: string;
  title?: string;
  tier?: number;
  experiment?: boolean;
  interactive?: boolean;
  template?: string;
}

export class CawsInit {
  private configManager: CawsConfigManager;

  constructor() {
    this.configManager = new CawsConfigManager();
  }

  async initialize(options: InitOptions): Promise<void> {
    const config = this.configManager.getConfig();

    // Ensure .caws directory exists
    const cawsDir = config.cawsDirectory;
    if (!fs.existsSync(cawsDir)) {
      fs.mkdirSync(cawsDir, { recursive: true });
    }

    // Generate working spec
    const workingSpecPath = config.workingSpecPath;
    if (fs.existsSync(workingSpecPath)) {
      console.warn(`⚠️  Working spec already exists at ${workingSpecPath}`);
      console.warn("Use --force to overwrite");
      return;
    }

    let specContent: string;

    if (options.interactive) {
      specContent = await this.generateInteractiveSpec(options);
    } else {
      specContent = this.generateSpecFromOptions(options);
    }

    fs.writeFileSync(workingSpecPath, specContent, "utf-8");
    console.log(`✅ Created working spec at ${workingSpecPath}`);

    // Initialize waivers file if it doesn't exist
    const waiversPath = config.waiversPath;
    if (waiversPath && !fs.existsSync(waiversPath)) {
      fs.writeFileSync(
        waiversPath,
        "# CAWS Waivers\n# Add waiver entries here\n",
        "utf-8"
      );
      console.log(`✅ Initialized waivers file at ${waiversPath}`);
    }

    // Create basic directory structure
    this.ensureDirectories();
  }

  private generateInteractiveSpec(options: InitOptions): string {
    // Simplified interactive mode - for now just use defaults
    // TODO: Add proper interactive prompts when prompts package is available
    console.log(
      "⚠️  Interactive mode not yet implemented. Using provided options or defaults."
    );

    return this.generateSpecContent({
      featureId: options.featureId || "FEAT-001",
      title: options.title || "New Feature",
      tier: options.tier || 2,
      experiment: options.experiment || false,
    });
  }

  private generateSpecFromOptions(options: InitOptions): string {
    const defaults = {
      featureId: options.featureId || "FEAT-001",
      title: options.title || "New Feature",
      tier: options.tier || 2,
      experiment: options.experiment || false,
    };

    return this.generateSpecContent(defaults);
  }

  private generateSpecContent(params: {
    featureId: string;
    title: string;
    tier: number;
    experiment: boolean;
  }): string {
    const template = `# CAWS Working Specification
# Generated by CAWS init tool

id: "${params.featureId}"
title: "${params.title}"
risk_tier: ${params.tier}
scope:
  in:
    - "TODO: Define what is in scope"
  out:
    - "TODO: Define what is out of scope"
invariants:
  - "TODO: Add business rules that must always hold"
acceptance:
  - id: A1
    given: "TODO: Given condition"
    when: "TODO: When action occurs"
    then: "TODO: Then expected outcome"
non_functional:
  a11y:
    - "TODO: Accessibility requirements"
  perf:
    api_p95_ms: 250
    lcp_ms: 2000
  security:
    - "TODO: Security requirements"
contracts:
  - type: openapi
    path: "apps/contracts/${params.featureId.toLowerCase()}.yaml"
observability:
  logs:
    - "TODO: Log statements to add"
  metrics:
    - "TODO: Metrics to emit"
  traces:
    - "TODO: Trace spans to instrument"
migrations:
  - "TODO: Database migrations needed"
rollback:
  - "TODO: Rollback strategy"

# AI Assessment (optional - remove if not needed)
ai_assessment:
  confidence_level: 8
  uncertainty_areas: ["TODO: Areas where AI is uncertain"]
  recommended_pairing: false

${
  params.experiment
    ? `# Experiment Mode
experiment_mode: true
timeboxed_hours: 24

# Human Override (for special cases - remove if not needed)
# human_override:
#   approved_by: "your-username"
#   reason: "TODO: Reason for override"
#   waived_requirements: ["mutation_testing"]
#   expiry_date: "2025-12-31T23:59:59Z"
`
    : ""
}
`;

    return template;
  }

  private ensureDirectories(): void {
    const config = this.configManager.getConfig();
    const dirs = [
      path.dirname(config.workingSpecPath),
      path.dirname(config.provenancePath || ""),
      config.waiversPath ? path.dirname(config.waiversPath) : "",
      "reports",
      "reports/mutation",
      "coverage",
      "test-results",
    ].filter(Boolean);

    for (const dir of dirs) {
      if (dir && !fs.existsSync(dir)) {
        fs.mkdirSync(dir, { recursive: true });
      }
    }
  }
}

// CLI interface
if (import.meta.url === `file://${process.argv[1]}`) {
  const command = process.argv[2];

  switch (command) {
    case "spec":
    case "init": {
      const options: InitOptions = {};

      // Parse CLI arguments
      for (let i = 3; i < process.argv.length; i++) {
        const arg = process.argv[i];
        if (arg === "--interactive" || arg === "-i") {
          options.interactive = true;
        } else if (arg === "--experiment" || arg === "-e") {
          options.experiment = true;
        } else if (arg.startsWith("--id=")) {
          options.featureId = arg.split("=")[1];
        } else if (arg.startsWith("--title=")) {
          options.title = arg.split("=")[1];
        } else if (arg.startsWith("--tier=")) {
          options.tier = parseInt(arg.split("=")[1]);
        }
      }

      const initTool = new CawsInit();
      initTool.initialize(options).catch((error) => {
        console.error(`❌ Failed to initialize CAWS: ${error}`);
        process.exit(1);
      });
      break;
    }

    default:
      console.log("CAWS Initialization Tool");
      console.log("");
      console.log("Usage:");
      console.log("  init spec [options]    - Initialize CAWS working spec");
      console.log("  init                   - Alias for 'spec'");
      console.log("");
      console.log("Options:");
      console.log("  --interactive, -i      Interactive mode with prompts");
      console.log("  --experiment, -e       Mark as experimental feature");
      console.log("  --id=FEATURE-123       Set feature ID");
      console.log('  --title="Feature"       Set feature title');
      console.log("  --tier=1|2|3           Set risk tier");
      console.log("");
      console.log("Examples:");
      console.log("  init spec --interactive");
      console.log('  init spec --id=FEAT-123 --title="User Login" --tier=2');
      break;
  }
}
