# Example GitHub Actions workflow for pnpm (for reference)
name: CI with pnpm

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build frontend
        run: pnpm --filter rag_web_search_tool run build

      - name: Type check
        run: pnpm -w run typecheck

      - name: Run tests
        run: pnpm -w run test
